---
title: "License"
author: "Costa, W. G."
date: "`r Sys.Date()`"
site: workflowr::wflow_site
url: https://wevertongomescosta.github.io/Machine-learning-e-redes-neurais-artificiais-no-melhoramento-genetico-do-cafeeiro//
output:
  workflowr::wflow_html:
    toc: FALSE
editor_options:
  chunk_output_type: console
github-repo: wevertongomescosta/Genomic-prediction-through-machine-learning-and-neural-networks-for-traits-with-epistasis
---

Este material foi produzido por [Costa, W. G.](https://github.com/WevertonGomesCosta), está licenciado sob a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.

Isso significa que você é livre para:

- Compartilhar - copiar e redistribuir o material em qualquer formato ou mídia
- Adaptar - remixar, transformar e construir sobre o material

Desde que você siga os termos da licença:

- Atribuição - Você deve dar crédito apropriado, fornecer um link para a licença e indicar se foram feitas alterações. Deve fazê-lo de maneira razoável, mas não de forma a sugerir que o licenciante apoia você ou o seu uso
- Não Comercial - Você não pode usar o material para fins comerciais
- Compartilhamento pela mesma licença - Se você remixar, transformar ou construir sobre o material, deve distribuir suas contribuições sob a mesma licença que o original

Para mais informações, consulte a licença completa em:  
[https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.pt](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.pt)

---

This material was produced by [Costa, W. G.](https://github.com/WevertonGomesCosta), is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.

This means you are free to:

- Share - copy and redistribute material in any format or media
- Adapt - remix, transform and build on the material

As long as you follow the license terms:

- Attribution - You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use
- Non-Commercial - You may not use the material for commercial purposes
- ShareAlike - If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original

For more information, see the full license at:  
[https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode)